name: SiegeGame
version: '${project.version}'
main: me.cedric.siegegame.SiegeGamePlugin
api-version: 1.19
softdepend:
  - PlaceholderAPI
depend:
  - NBTAPI
  - ProtocolLib
  - LunarClient-API
  - CombatLogX
